jwt:
  secret: "[a-zA-Z0-9._]^+$Guidlines89797887forAlphabeticalArraNumeralsandOtherSymbo$"

server:
  port: 8081
  error:
     path: "/error"

  #Option 1
  #error:
  #  whitelabel:
  #    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      #overwrites existing tables and creates new table(s) when the Applications is being launched
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

  #Option 2
  # The below 4 configuration lines configure Spring to throw the handler not found exception and
  # not catch it by itself (Whitelabel Error Page)
  # mvc:
  #   throw-exception-if-no-handler-found: true
  # web:
  #   resources:
  #     add-mappings: false
